server:
  port: 8080

spring:
  servlet:
    multipart:
      max-request-size: 200MB
      max-file-size: 20MB
  # 数据库数据源配置
  datasource:
    url: jdbc:mysql://localhost:3306/imgup_db?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: xxxx # <-- 填写你的数据库用户名
    password: xxxxxxxx # <-- 修改为你的数据库密码
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

# MyBatis-Plus 配置
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml # Mapper XML文件位置
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 打印SQL日志到控制台
  global-config:
    db-config:
      # 逻辑删除配置
      logic-delete-field: deleted # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

# Jasypt 加密配置
jasypt:
  encryptor:
    password: "Xt>sr)W67[Ny,e5sHFUy7{:W(,Jr(vrQ" # <-- 修改为一个强随机密钥，用于加密图床配置

# 自定义JWT配置
jwt:
  secret: "4JfTqMBa8cOyFfjCDzOGvQ13WC4v+Z2rmSVQlj1kAiM=" # Base64
  accessTokenExpiration: 900000 # accessTokenExpiration有效期，这里为 15 minutes
  refreshTokenExpiration: 604800000 # refreshTokenExpiration有效期，这里为 7 days

logging:
  level:
    com:
      chaos: debug

debug: true
